 
 steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/splendid-world-366611/cloudrun:$SHORT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/splendid-world-366611/cloudrun:$SHORT_SHA',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'cloud-run-continuous-deployment-example',
        '--image=gcr.io/splendid-world-366611/cloudrun:$SHORT_SHA',
        '--region=us-central1',
      ]
